[alias]
xtask = "run --package xtask --"

[target.'cfg(all())']
rustflags = [
  "-Dwarnings",
  "-Dclippy::all",
  "-Dclippy::cargo",
  "-Dclippy::correctness",
  "-Dclippy::suspicious",
  "-Dclippy::pedantic",
  # Docs
  "-Aclippy::missing_errors_doc",
  "-Aclippy::missing_panics_doc",
  # Cargo
  "-Aclippy::multiple_crate_versions",
  # Pedantic - not useful for this project
  "-Aclippy::too_many_lines",
  "-Aclippy::cast_possible_truncation",
  "-Aclippy::similar_names",
]
